# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

languages = Language.create([
                                {locale: 'ar', name: 'Arabic'},
                                {locale: 'ar_AE', name: 'Arabic (United Arab Emirates)'},
                                {locale: 'ar_BH', name: 'Arabic (Bahrain)'},
                                {locale: 'ar_DZ', name: 'Arabic (Algeria)'},
                                {locale: 'ar_EG', name: 'Arabic (Egypt)'},
                                {locale: 'ar_IQ', name: 'Arabic (Iraq)'},
                                {locale: 'ar_JO', name: 'Arabic (Jordan)'},
                                {locale: 'ar_KW', name: 'Arabic (Kuwait)'},
                                {locale: 'ar_LB', name: 'Arabic (Lebanon)'},
                                {locale: 'ar_LY', name: 'Arabic (Libya)'},
                                {locale: 'ar_MA', name: 'Arabic (Morocco)'},
                                {locale: 'ar_OM', name: 'Arabic (Oman)'},
                                {locale: 'ar_QA', name: 'Arabic (Qatar)'},
                                {locale: 'ar_SA', name: 'Arabic (Saudi Arabia)'},
                                {locale: 'ar_SD', name: 'Arabic (Sudan)'},
                                {locale: 'ar_SY', name: 'Arabic (Syria)'},
                                {locale: 'ar_TN', name: 'Arabic (Tunisia)'},
                                {locale: 'ar_YE', name: 'Arabic (Yemen)'},
                                {locale: 'be', name: 'Belarusian'},
                                {locale: 'be_BY', name: 'Belarusian (Belarus)'},
                                {locale: 'bg', name: 'Bulgarian'},
                                {locale: 'bg_BG', name: 'Bulgarian (Bulgaria)'},
                                {locale: 'ca', name: 'Catalan'},
                                {locale: 'ca_ES', name: 'Catalan (Spain)'},
                                {locale: 'cs', name: 'Czech'},
                                {locale: 'cs_CZ', name: 'Czech (Czech Republic)'},
                                {locale: 'da', name: 'Danish'},
                                {locale: 'da_DK', name: 'Danish (Denmark)'},
                                {locale: 'de', name: 'German'},
                                {locale: 'de_AT', name: 'German (Austria)'},
                                {locale: 'de_CH', name: 'German (Switzerland)'},
                                {locale: 'de_DE', name: 'German (Germany)'},
                                {locale: 'de_LU', name: 'German (Luxembourg)'},
                                {locale: 'el', name: 'Greek'},
                                {locale: 'el_CY', name: 'Greek (Cyprus)'},
                                {locale: 'el_GR', name: 'Greek (Greece)'},
                                {locale: 'en', name: 'English'},
                                {locale: 'en_AU', name: 'English (Australia)'},
                                {locale: 'en_CA', name: 'English (Canada)'},
                                {locale: 'en_GB', name: 'English (United Kingdom)'},
                                {locale: 'en_IE', name: 'English (Ireland)'},
                                {locale: 'en_IN', name: 'English (India)'},
                                {locale: 'en_MT', name: 'English (Malta)'},
                                {locale: 'en_NZ', name: 'English (New Zealand)'},
                                {locale: 'en_PH', name: 'English (Philippines)'},
                                {locale: 'en_SG', name: 'English (Singapore)'},
                                {locale: 'en_US', name: 'English (United States)'},
                                {locale: 'en_ZA', name: 'English (South Africa)'},
                                {locale: 'es', name: 'Spanish'},
                                {locale: 'es_AR', name: 'Spanish (Argentina)'},
                                {locale: 'es_BO', name: 'Spanish (Bolivia)'},
                                {locale: 'es_CL', name: 'Spanish (Chile)'},
                                {locale: 'es_CO', name: 'Spanish (Colombia)'},
                                {locale: 'es_CR', name: 'Spanish (Costa Rica)'},
                                {locale: 'es_DO', name: 'Spanish (Dominican Republic)'},
                                {locale: 'es_EC', name: 'Spanish (Ecuador)'},
                                {locale: 'es_ES', name: 'Spanish (Spain)'},
                                {locale: 'es_GT', name: 'Spanish (Guatemala)'},
                                {locale: 'es_HN', name: 'Spanish (Honduras)'},
                                {locale: 'es_MX', name: 'Spanish (Mexico)'},
                                {locale: 'es_NI', name: 'Spanish (Nicaragua)'},
                                {locale: 'es_PA', name: 'Spanish (Panama)'},
                                {locale: 'es_PE', name: 'Spanish (Peru)'},
                                {locale: 'es_PR', name: 'Spanish (Puerto Rico)'},
                                {locale: 'es_PY', name: 'Spanish (Paraguay)'},
                                {locale: 'es_SV', name: 'Spanish (El Salvador)'},
                                {locale: 'es_US', name: 'Spanish (United States)'},
                                {locale: 'es_UY', name: 'Spanish (Uruguay)'},
                                {locale: 'es_VE', name: 'Spanish (Venezuela)'},
                                {locale: 'et', name: 'Estonian'},
                                {locale: 'et_EE', name: 'Estonian (Estonia)'},
                                {locale: 'fi', name: 'Finnish'},
                                {locale: 'fi_FI', name: 'Finnish (Finland)'},
                                {locale: 'fr', name: 'French'},
                                {locale: 'fr_BE', name: 'French (Belgium)'},
                                {locale: 'fr_CA', name: 'French (Canada)'},
                                {locale: 'fr_CH', name: 'French (Switzerland)'},
                                {locale: 'fr_FR', name: 'French (France)'},
                                {locale: 'fr_LU', name: 'French (Luxembourg)'},
                                {locale: 'ga', name: 'Irish'},
                                {locale: 'ga_IE', name: 'Irish (Ireland)'},
                                {locale: 'hi_IN', name: 'Hindi (India)'},
                                {locale: 'hr', name: 'Croatian'},
                                {locale: 'hr_HR', name: 'Croatian (Croatia)'},
                                {locale: 'hu', name: 'Hungarian'},
                                {locale: 'hu_HU', name: 'Hungarian (Hungary)'},
                                {locale: 'in', name: 'Indonesian'},
                                {locale: 'in_ID', name: 'Indonesian (Indonesia)'},
                                {locale: 'is', name: 'Icelandic'},
                                {locale: 'is_IS', name: 'Icelandic (Iceland)'},
                                {locale: 'it', name: 'Italian'},
                                {locale: 'it_CH', name: 'Italian (Switzerland)'},
                                {locale: 'it_IT', name: 'Italian (Italy)'},
                                {locale: 'iw', name: 'Hebrew'},
                                {locale: 'iw_IL', name: 'Hebrew (Israel)'},
                                {locale: 'ja', name: 'Japanese'},
                                {locale: 'ja_JP', name: 'Japanese (Japan)'},
                                {locale: 'ja_JP_JP_#u-ca-japanese', name: 'Japanese (Japan,JP)'},
                                {locale: 'ko', name: 'Korean'},
                                {locale: 'ko_KR', name: 'Korean (South Korea)'},
                                {locale: 'lt', name: 'Lithuanian'},
                                {locale: 'lt_LT', name: 'Lithuanian (Lithuania)'},
                                {locale: 'lv', name: 'Latvian'},
                                {locale: 'lv_LV', name: 'Latvian (Latvia)'},
                                {locale: 'mk', name: 'Macedonian'},
                                {locale: 'mk_MK', name: 'Macedonian (Macedonia)'},
                                {locale: 'ms', name: 'Malay'},
                                {locale: 'ms_MY', name: 'Malay (Malaysia)'},
                                {locale: 'mt', name: 'Maltese'},
                                {locale: 'mt_MT', name: 'Maltese (Malta)'},
                                {locale: 'nl', name: 'Dutch'},
                                {locale: 'nl_BE', name: 'Dutch (Belgium)'},
                                {locale: 'nl_NL', name: 'Dutch (Netherlands)'},
                                {locale: 'no', name: 'Norwegian'},
                                {locale: 'no_NO', name: 'Norwegian (Norway)'},
                                {locale: 'no_NO_NY', name: 'Norwegian (Norway,Nynorsk)'},
                                {locale: 'pl', name: 'Polish'},
                                {locale: 'pl_PL', name: 'Polish (Poland)'},
                                {locale: 'pt', name: 'Portuguese'},
                                {locale: 'pt_BR', name: 'Portuguese (Brazil)'},
                                {locale: 'pt_PT', name: 'Portuguese (Portugal)'},
                                {locale: 'ro', name: 'Romanian'},
                                {locale: 'ro_RO', name: 'Romanian (Romania)'},
                                {locale: 'ru', name: 'Russian'},
                                {locale: 'ru_RU', name: 'Russian (Russia)'},
                                {locale: 'sk', name: 'Slovak'},
                                {locale: 'sk_SK', name: 'Slovak (Slovakia)'},
                                {locale: 'sl', name: 'Slovenian'},
                                {locale: 'sl_SI', name: 'Slovenian (Slovenia)'},
                                {locale: 'sq', name: 'Albanian'},
                                {locale: 'sq_AL', name: 'Albanian (Albania)'},
                                {locale: 'sr', name: 'Serbian'},
                                {locale: 'sr_BA', name: 'Serbian (Bosnia and Herzegovina)'},
                                {locale: 'sr_BA_#Latn', name: 'Serbian (Latin,Bosnia and Herzegovina)'},
                                {locale: 'sr_CS', name: 'Serbian (Serbia and Montenegro)'},
                                {locale: 'sr_ME', name: 'Serbian (Montenegro)'},
                                {locale: 'sr_ME_#Latn', name: 'Serbian (Latin,Montenegro)'},
                                {locale: 'sr_RS', name: 'Serbian (Serbia)'},
                                {locale: 'sr_RS_#Latn', name: 'Serbian (Latin,Serbia)'},
                                {locale: 'sr__#Latn', name: 'Serbian (Latin)'},
                                {locale: 'sv', name: 'Swedish'},
                                {locale: 'sv_SE', name: 'Swedish (Sweden)'},
                                {locale: 'th', name: 'Thai'},
                                {locale: 'th_TH', name: 'Thai (Thailand)'},
                                {locale: 'th_TH_TH_#u-nu-thai', name: 'Thai (Thailand,TH)'},
                                {locale: 'tr', name: 'Turkish'},
                                {locale: 'tr_TR', name: 'Turkish (Turkey)'},
                                {locale: 'uk', name: 'Ukrainian'},
                                {locale: 'uk_UA', name: 'Ukrainian (Ukraine)'},
                                {locale: 'vi', name: 'Vietnamese'},
                                {locale: 'vi_VN', name: 'Vietnamese (Vietnam)'},
                                {locale: 'zh', name: 'Chinese'},
                                {locale: 'zh_CN', name: 'Chinese (China)'},
                                {locale: 'zh_HK', name: 'Chinese (Hong Kong)'},
                                {locale: 'zh_SG', name: 'Chinese (Singapore)'},
                                {locale: 'zh_TW', name: 'Chinese (Taiwan)'}
                            ])