# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Language.delete_all
Language.create([
    {id: 1, locale: 'ar', name: 'Arabic'},
    {id: 2, locale: 'ar_AE', name: 'Arabic (United Arab Emirates)'},
    {id: 3, locale: 'ar_BH', name: 'Arabic (Bahrain)'},
    {id: 4, locale: 'ar_DZ', name: 'Arabic (Algeria)'},
    {id: 5, locale: 'ar_EG', name: 'Arabic (Egypt)'},
    {id: 6, locale: 'ar_IQ', name: 'Arabic (Iraq)'},
    {id: 7, locale: 'ar_JO', name: 'Arabic (Jordan)'},
    {id: 8, locale: 'ar_KW', name: 'Arabic (Kuwait)'},
    {id: 9, locale: 'ar_LB', name: 'Arabic (Lebanon)'},
    {id: 10, locale: 'ar_LY', name: 'Arabic (Libya)'},
    {id: 11, locale: 'ar_MA', name: 'Arabic (Morocco)'},
    {id: 12, locale: 'ar_OM', name: 'Arabic (Oman)'},
    {id: 13, locale: 'ar_QA', name: 'Arabic (Qatar)'},
    {id: 14, locale: 'ar_SA', name: 'Arabic (Saudi Arabia)'},
    {id: 15, locale: 'ar_SD', name: 'Arabic (Sudan)'},
    {id: 16, locale: 'ar_SY', name: 'Arabic (Syria)'},
    {id: 17, locale: 'ar_TN', name: 'Arabic (Tunisia)'},
    {id: 18, locale: 'ar_YE', name: 'Arabic (Yemen)'},
    {id: 19, locale: 'be', name: 'Belarusian'},
    {id: 20, locale: 'be_BY', name: 'Belarusian (Belarus)'},
    {id: 21, locale: 'bg', name: 'Bulgarian'},
    {id: 22, locale: 'bg_BG', name: 'Bulgarian (Bulgaria)'},
    {id: 23, locale: 'ca', name: 'Catalan'},
    {id: 24, locale: 'ca_ES', name: 'Catalan (Spain)'},
    {id: 25, locale: 'cs', name: 'Czech'},
    {id: 26, locale: 'cs_CZ', name: 'Czech (Czech Republic)'},
    {id: 27, locale: 'da', name: 'Danish'},
    {id: 28, locale: 'da_DK', name: 'Danish (Denmark)'},
    {id: 29, locale: 'de', name: 'German'},
    {id: 30, locale: 'de_AT', name: 'German (Austria)'},
    {id: 31, locale: 'de_CH', name: 'German (Switzerland)'},
    {id: 32, locale: 'de_DE', name: 'German (Germany)'},
    {id: 33, locale: 'de_LU', name: 'German (Luxembourg)'},
    {id: 34, locale: 'el', name: 'Greek'},
    {id: 35, locale: 'el_CY', name: 'Greek (Cyprus)'},
    {id: 36, locale: 'el_GR', name: 'Greek (Greece)'},
    {id: 37, locale: 'en', name: 'English'},
    {id: 38, locale: 'en_AU', name: 'English (Australia)'},
    {id: 39, locale: 'en_CA', name: 'English (Canada)'},
    {id: 40, locale: 'en_GB', name: 'English (United Kingdom)'},
    {id: 41, locale: 'en_IE', name: 'English (Ireland)'},
    {id: 42, locale: 'en_IN', name: 'English (India)'},
    {id: 43, locale: 'en_MT', name: 'English (Malta)'},
    {id: 44, locale: 'en_NZ', name: 'English (New Zealand)'},
    {id: 45, locale: 'en_PH', name: 'English (Philippines)'},
    {id: 46, locale: 'en_SG', name: 'English (Singapore)'},
    {id: 47, locale: 'en_US', name: 'English (United States)'},
    {id: 48, locale: 'en_ZA', name: 'English (South Africa)'},
    {id: 49, locale: 'es', name: 'Spanish'},
    {id: 50, locale: 'es_AR', name: 'Spanish (Argentina)'},
    {id: 51, locale: 'es_BO', name: 'Spanish (Bolivia)'},
    {id: 52, locale: 'es_CL', name: 'Spanish (Chile)'},
    {id: 53, locale: 'es_CO', name: 'Spanish (Colombia)'},
    {id: 54, locale: 'es_CR', name: 'Spanish (Costa Rica)'},
    {id: 55, locale: 'es_DO', name: 'Spanish (Dominican Republic)'},
    {id: 56, locale: 'es_EC', name: 'Spanish (Ecuador)'},
    {id: 57, locale: 'es_ES', name: 'Spanish (Spain)'},
    {id: 58, locale: 'es_GT', name: 'Spanish (Guatemala)'},
    {id: 59, locale: 'es_HN', name: 'Spanish (Honduras)'},
    {id: 60, locale: 'es_MX', name: 'Spanish (Mexico)'},
    {id: 61, locale: 'es_NI', name: 'Spanish (Nicaragua)'},
    {id: 62, locale: 'es_PA', name: 'Spanish (Panama)'},
    {id: 63, locale: 'es_PE', name: 'Spanish (Peru)'},
    {id: 64, locale: 'es_PR', name: 'Spanish (Puerto Rico)'},
    {id: 65, locale: 'es_PY', name: 'Spanish (Paraguay)'},
    {id: 66, locale: 'es_SV', name: 'Spanish (El Salvador)'},
    {id: 67, locale: 'es_US', name: 'Spanish (United States)'},
    {id: 68, locale: 'es_UY', name: 'Spanish (Uruguay)'},
    {id: 69, locale: 'es_VE', name: 'Spanish (Venezuela)'},
    {id: 70, locale: 'et', name: 'Estonian'},
    {id: 71, locale: 'et_EE', name: 'Estonian (Estonia)'},
    {id: 72, locale: 'fi', name: 'Finnish'},
    {id: 73, locale: 'fi_FI', name: 'Finnish (Finland)'},
    {id: 74, locale: 'fr', name: 'French'},
    {id: 75, locale: 'fr_BE', name: 'French (Belgium)'},
    {id: 76, locale: 'fr_CA', name: 'French (Canada)'},
    {id: 77, locale: 'fr_CH', name: 'French (Switzerland)'},
    {id: 78, locale: 'fr_FR', name: 'French (France)'},
    {id: 79, locale: 'fr_LU', name: 'French (Luxembourg)'},
    {id: 80, locale: 'ga', name: 'Irish'},
    {id: 81, locale: 'ga_IE', name: 'Irish (Ireland)'},
    {id: 82, locale: 'hi_IN', name: 'Hindi (India)'},
    {id: 83, locale: 'hr', name: 'Croatian'},
    {id: 84, locale: 'hr_HR', name: 'Croatian (Croatia)'},
    {id: 85, locale: 'hu', name: 'Hungarian'},
    {id: 86, locale: 'hu_HU', name: 'Hungarian (Hungary)'},
    {id: 87, locale: 'in', name: 'Indonesian'},
    {id: 88, locale: 'in_ID', name: 'Indonesian (Indonesia)'},
    {id: 89, locale: 'is', name: 'Icelandic'},
    {id: 90, locale: 'is_IS', name: 'Icelandic (Iceland)'},
    {id: 91, locale: 'it', name: 'Italian'},
    {id: 92, locale: 'it_CH', name: 'Italian (Switzerland)'},
    {id: 93, locale: 'it_IT', name: 'Italian (Italy)'},
    {id: 94, locale: 'iw', name: 'Hebrew'},
    {id: 95, locale: 'iw_IL', name: 'Hebrew (Israel)'},
    {id: 96, locale: 'ja', name: 'Japanese'},
    {id: 97, locale: 'ja_JP', name: 'Japanese (Japan)'},
    {id: 98, locale: 'ja_JP_JP_#u-ca-japanese', name: 'Japanese (Japan,JP)'},
    {id: 99, locale: 'ko', name: 'Korean'},
    {id: 100, locale: 'ko_KR', name: 'Korean (South Korea)'},
    {id: 101, locale: 'lt', name: 'Lithuanian'},
    {id: 102, locale: 'lt_LT', name: 'Lithuanian (Lithuania)'},
    {id: 103, locale: 'lv', name: 'Latvian'},
    {id: 104, locale: 'lv_LV', name: 'Latvian (Latvia)'},
    {id: 105, locale: 'mk', name: 'Macedonian'},
    {id: 106, locale: 'mk_MK', name: 'Macedonian (Macedonia)'},
    {id: 107, locale: 'ms', name: 'Malay'},
    {id: 108, locale: 'ms_MY', name: 'Malay (Malaysia)'},
    {id: 109, locale: 'mt', name: 'Maltese'},
    {id: 110, locale: 'mt_MT', name: 'Maltese (Malta)'},
    {id: 111, locale: 'nl', name: 'Dutch'},
    {id: 112, locale: 'nl_BE', name: 'Dutch (Belgium)'},
    {id: 113, locale: 'nl_NL', name: 'Dutch (Netherlands)'},
    {id: 114, locale: 'no', name: 'Norwegian'},
    {id: 115, locale: 'no_NO', name: 'Norwegian (Norway)'},
    {id: 116, locale: 'no_NO_NY', name: 'Norwegian (Norway,Nynorsk)'},
    {id: 117, locale: 'pl', name: 'Polish'},
    {id: 118, locale: 'pl_PL', name: 'Polish (Poland)'},
    {id: 119, locale: 'pt', name: 'Portuguese'},
    {id: 120, locale: 'pt_BR', name: 'Portuguese (Brazil)'},
    {id: 121, locale: 'pt_PT', name: 'Portuguese (Portugal)'},
    {id: 122, locale: 'ro', name: 'Romanian'},
    {id: 123, locale: 'ro_RO', name: 'Romanian (Romania)'},
    {id: 124, locale: 'ru', name: 'Russian'},
    {id: 125, locale: 'ru_RU', name: 'Russian (Russia)'},
    {id: 126, locale: 'sk', name: 'Slovak'},
    {id: 127, locale: 'sk_SK', name: 'Slovak (Slovakia)'},
    {id: 128, locale: 'sl', name: 'Slovenian'},
    {id: 129, locale: 'sl_SI', name: 'Slovenian (Slovenia)'},
    {id: 130, locale: 'sq', name: 'Albanian'},
    {id: 131, locale: 'sq_AL', name: 'Albanian (Albania)'},
    {id: 132, locale: 'sr', name: 'Serbian'},
    {id: 133, locale: 'sr_BA', name: 'Serbian (Bosnia and Herzegovina)'},
    {id: 134, locale: 'sr_BA_#Latn', name: 'Serbian (Latin,Bosnia and Herzegovina)'},
    {id: 135, locale: 'sr_CS', name: 'Serbian (Serbia and Montenegro)'},
    {id: 136, locale: 'sr_ME', name: 'Serbian (Montenegro)'},
    {id: 137, locale: 'sr_ME_#Latn', name: 'Serbian (Latin,Montenegro)'},
    {id: 138, locale: 'sr_RS', name: 'Serbian (Serbia)'},
    {id: 139, locale: 'sr_RS_#Latn', name: 'Serbian (Latin,Serbia)'},
    {id: 140, locale: 'sr__#Latn', name: 'Serbian (Latin)'},
    {id: 141, locale: 'sv', name: 'Swedish'},
    {id: 142, locale: 'sv_SE', name: 'Swedish (Sweden)'},
    {id: 143, locale: 'th', name: 'Thai'},
    {id: 144, locale: 'th_TH', name: 'Thai (Thailand)'},
    {id: 145, locale: 'th_TH_TH_#u-nu-thai', name: 'Thai (Thailand,TH)'},
    {id: 146, locale: 'tr', name: 'Turkish'},
    {id: 147, locale: 'tr_TR', name: 'Turkish (Turkey)'},
    {id: 148, locale: 'uk', name: 'Ukrainian'},
    {id: 149, locale: 'uk_UA', name: 'Ukrainian (Ukraine)'},
    {id: 150, locale: 'vi', name: 'Vietnamese'},
    {id: 151, locale: 'vi_VN', name: 'Vietnamese (Vietnam)'},
    {id: 152, locale: 'zh', name: 'Chinese'},
    {id: 153, locale: 'zh_CN', name: 'Chinese (China)'},
    {id: 154, locale: 'zh_HK', name: 'Chinese (Hong Kong)'},
    {id: 155, locale: 'zh_SG', name: 'Chinese (Singapore)'},
    {id: 156, locale: 'zh_TW', name: 'Chinese (Taiwan)'}
])

Role.delete_all
Role.create([
    {id: 1, name: 'administrator'},
    {id: 2, name: 'projectadmin'},
    {id: 3, name: 'translator'}
])
